### ISSUE TITLE
plugins and css not working anymore

### ISSUE THREAD

**Issue by ekrej** [DiscordInjections/DiscordInjections#103]
some parts of the theme I use werent working anymore and the plugins didnt show up, when I tried to reinject discordInjections even what was left of the theme was not there anymore. I was wondering if anyone had this problem an knows what to do.

**Comment by theGordHoard** [comment]
There was a recent Discord update that broke many themes and changes CSS classes. As for the plugins, what version of DiscordInjections are you using?

**Comment by xXBuilderBXx** [comment]
Afaik plugins do not work anymore and not sure if their is going to be an update to fix this

**Comment by theGordHoard** [comment]
Plugins do work, there are just not many for v4 yet. If you are still using v3, which has used to have the best plugins support, the recent update broke the injection on it, and v4 is the only version that works.

**Comment by theGordHoard** [comment]
v4 and v3 plugins are not compatible

**Comment by ekrej** [comment]
I'm using v4 as of yesterday, hoping the update would fic it,  but thats when all the css dissapeared and the menu didnt show up anymore. But if tit is a compatibility issue i'll just have to wait, I guess

**Comment by cking** [comment]
@ekrej there is not a single localdata clear or merge option. you have to manually do that. it is not planned to be added in the near future.
