### ISSUE TITLE
[v4] Uncaught (in promise) TypeError: expecting an array or an iterable object but got [object Null]

### ISSUE THREAD

**Issue by Cynosphere** [DiscordInjections/DiscordInjections#104]
`D:\Discord\di\engine\index.js:116 Uncaught (in promise) TypeError: expecting an array or an iterable object but got [object Null]`
Nothing from DI fully loads because of this.

**Comment by cking** [comment]
still a thing in latest version? if so please give a full stacktrace?

**Comment by cking** [comment]
no input given, will close
