### ISSUE TITLE
Themes not loaded on start

### ISSUE THREAD

**Issue by nycex** [DiscordInjections/DiscordInjections#119]
## Expected Behavior
So, I want DI to install themes, and load them, when I restart DI.

## Current Behavior
[Here](https://tinyimg.io/i/msdUo0N.png) you can see a ls of ~/.config/discordcanary/plugins/.
And [here](https://tinyimg.io/i/lP4WTcX.png) you can see which one show, after i restart DI.
[Here](http://ix.io/1aLf) is also a paste of the error I get.
As you can see, there the themes aren't loaded after a restart.

## Your Environment
* DI Version: Latest
* Discord version: 0.0.50 Latest Canary
* Operating System and version: Arch Linux
* Used Plugins: Part of the bug

Edit: [Here](http://ix.io/1aMD) is the complete log.

**Comment by cking** [comment]
full console log pls

**Comment by cking** [comment]
also that error is completly unrelated and non breaking. so full log or close as invalid.

**Comment by nycex** [comment]
[Here](http://ix.io/1aMD) is the complete log.

**Comment by cking** [comment]
enable debug output, restart discord and upload full log (to enable debug mode, go into the config.json, add a line `"debug": true,` right after the `{`

**Comment by nycex** [comment]
Okay, [here](http://ix.io/1aMY) it is

**Comment by cking** [comment]
that is noit the full log.
make sure you upload the full log and your hoster isnt stripping things off.
there should be at bare minimum ~50-100 lines

**Comment by nycex** [comment]
My hoster isn't stripping anything, that was the complete log. I restarted again, [now Its 69 lines](http://ix.io/1aN1):

**Comment by nycex** [comment]
Cannot reproduce after reinjecting with 1226a0acfbefa5b267b6b791324985c6245bcf2e
