### ISSUE TITLE
DI v4 broke

### ISSUE THREAD

**Issue by martmists** [DiscordInjections/DiscordInjections#120]
Your issue may already be reported!
Please search on the [issue tracker](../) before creating one.

## Expected Behavior
Discord loads

## Current Behavior
![image](https://user-images.githubusercontent.com/16361449/40305553-43c51068-5cfb-11e8-9e37-720b7a8a672f.png)
Text version: [Hastebin](https://hastebin.com/ucoyabegan.pas)

## Possible Solution
No clue

## Steps to Reproduce (for bugs)
1. Clone DI (v4)
2. npm i && npm run inject
3. Launch Discord

## Context
See above

## Your Environment
* DI Version: da49f008d12e93ec880ed618a94157867e08be92
* Discord version: `Build Number: 15701, Version Hash: 13ccda23491befce50104bb08aabcb51c0333837`
* Operating System and version: Arch Linux x86_64, all packages updated
* Used Plugins: OpenDI (tried with that disabled too)

**Comment by cking** [comment]
should be fixed with 7695248

**Comment by cking** [comment]
also next time, text log in debug mode

**Comment by martmists** [comment]
how can I enable debug mode when I can't use //debug?

**Comment by cking** [comment]
`"debug": true` in config.json - as explained in config.json.template
