### ISSUE TITLE
Typo on latest release (24/06/2018)

### ISSUE THREAD

**Issue by missingbinaries** [DiscordInjections/DiscordInjections#130]
## Observed Behavior
On the releases page, I've noticed that it says 'fighti8ng' and I presume this is a typo that was intended to be 'fighting'.

## Current Behavior
N/A (?)

## Possible Solution
Change the releases page(?)

## Steps to Reproduce (for bugs)
N/A

## Context
N/A

## Your Environment
N/A - not a bug within the code

* DI Version:
* Discord version:
* Operating System and version:
* Used Plugins:

**Comment by cking** [comment]
thanks, done
