### ISSUE TITLE
Setting transparency to true does not actually make discord transparent

### ISSUE THREAD

**Issue by martmists** [DiscordInjections/DiscordInjections#132]
## Expected Behavior
In combination with Alexflipnote's `Discord_Theme.css` and companion `Transparent.css`, all elements become transparent, and with `transparency enabled in the DI config, the window should be transparent if supported by WM, which it is.

## Current Behavior
The window is not transparent. Instead, there's a black background.

## Your Environment
* DI Version: latest
* Discord version: latest
* Operating System and version: Arch Linux (all packages up to date)
* Used Plugins: Core plugins

**Comment by cking** [comment]
Which window manager?
Which transparency compositor?
Which tk for wm and compositor?
Xorg, darwin or mir?

more information please for your setup?
also latest version of DI from what date? if you are using git, then add the commit hash
which discord version from what date? try to add the modules version or something uniqly identifyable. also is it ptb, stable or canary?

**Comment by cking** [comment]
i assume this isnt relevant anymore
