### ISSUE TITLE
Can't Install DI 4.0

### ISSUE THREAD

**Issue by MiagoMeowsome** [DiscordInjections/DiscordInjections#133]
## Expected Behavior

Getting DI Installed

## Current Behavior

The installation doesn't finish because of an error 
Command Prompt : https://i.imgur.com/iMCsrzs.png
Error Log : https://pastebin.com/TqLkwZgm

## Your Environment

* DI Version: 4.0
* Discord version: 18362 Stable
* Operating System and version: Windows 10 10.0.17.134

**Comment by cking** [comment]
What's your node version? Are you using a got checkout or a release version?

**Comment by MiagoMeowsome** [comment]
I'm on Node v10.3.0 and using the release version

**Comment by cking** [comment]
ill take a look later this week or next

**Comment by cking** [comment]
the packaged distribution is removed for now. this is not a fix per se but i cant work on it right now. you have to call `npm install` before `npm run inject` and hope for the best.
