### ISSUE TITLE
sendLocalMessage throws cannot read property error

### ISSUE THREAD

**Issue by checkium** [DiscordInjections/DiscordInjections#135]
## Expected Behavior
The method should send a local message with the specified content

## Current Behavior
components/plugin.js line 282 throws the error `TypeError: Cannot read property 'receiveMessage' of undefined` due to this.manager.get('hooks')._messageHandler being undefined

## Steps to Reproduce (for bugs)
1. Use sendLocalMessage in a plugin, such as using it in a command and executing the specified command.

## Your Environment

* DI Version: 4.0.0
* Discord version: Canary 19526
* Operating System and version: Windows 10
* Used Plugins: custom plugins

**Comment by cking** [comment]
Please Append a debug log as explained in the guide

**Comment by checkium** [comment]
https://hastebin.com/raw/opudixibaw.log

**Comment by cking** [comment]
are you setting the correct dependencies? your log says it has found the receiveMessage function? i need to see where you call it and how your package.json looks like. please send a mwe

**Comment by cking** [comment]
i assume this isnt relevant anymore.
