### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by martmists** [DiscordInjections/DiscordInjections#137]
## Expected Behavior
DI launches fine

## Current Behavior
![image](https://user-images.githubusercontent.com/16361449/44389901-58b1ee00-a52c-11e8-9697-821e0a7c03f1.png)

## Steps to Reproduce (for bugs)
1. Install DI
2. Get these wiped for some unknown reason 
![image](https://user-images.githubusercontent.com/16361449/44389934-71ba9f00-a52c-11e8-89a8-0b54ef12809a.png)
3. Launch discord

## Your Environment
* DI Version: tag v4.0.1
* Discord version: Release Channel: canary, Build Number: 22283, Version Hash: cc68535efeb13cba9796ee0c4299e603b72bdf94
* Operating System and version: Arch Linux (All packages up to date)
* Used Plugins: None

**Comment by cking** [comment]
Can't verify on Ubuntu, more user input needed.
![](https://kura.is-pretty.sexy/41b435.png)
What is the full log output from webinspector and the terminal?

**Comment by martmists** [comment]
[webinspector](https://gist.github.com/martmists/2a78c4d1015f7e2313a911630776b58c)
Terminal:
```
DiscordCanary 0.0.53
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/mart/.config/discordcanary/0.0.53/modules
[Modules] Module installed file path: /home/mart/.config/discordcanary/0.0.53/modules/installed.json
[Modules] Module download path: /home/mart/.config/discordcanary/0.0.53/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/canary/versions.json
[Modules] No module updates available.
```

**Comment by martmists** [comment]
Fixed by removing `~/.config/discordcanary/plugins` which was keeping track of stuff that wasnt in the DI application variable.
