### ISSUE TITLE
DI fails to load as desktop application

### ISSUE THREAD

**Issue by martmists** [DiscordInjections/DiscordInjections#138]
## Expected Behavior
DI Head works *decently* fine
(Same issue happens with V4.* tags)

## Current Behavior
Discord gets detected as web version rather than desktop version.
- Settings tabs are exactly the same
- Popup saying "Need push to talk? get the desktop app"

## Possible Solution
Unknown, looking into it. Possibly missing a dependency DI uses (package, not npm, I did run npm i) required for DI to work

## Steps to Reproduce (for bugs)
1. Install DI Head
2. Run discordcanary
3. check settings tabs and compare with web version

## Your Environment

* DI Version: Head @ 006c08a2c10eebe96532bb125c1ff94bbfad9db3
* Discord version: `[BUILD INFO] Release Channel: canary, Build Number: 24492, Version Hash: 13b18e92b24be4f83ed124a4d09b6267810b7605`
* Operating System and version: Arch Linux (Latest, updated)
* Used Plugins: System plugins

**Comment by intrnl** [comment]
iirc messing with preload causes this

**Comment by cking** [comment]
i am using the native preload though. might be that they broke it in the past, latest commit changes the way i load the native preload script, please check if it works with head.

**Comment by martmists** [comment]
Fixed in 255eb9b7c8c742cd0fc74d5330b15a9392171745 for me
