### ISSUE TITLE
Discord Injections Settings Tab Doesn't Appear on Other Languages

### ISSUE THREAD

**Issue by TheSheepGuy** [DiscordInjections/DiscordInjections#34]
If the language is set to anything but English UK/US, the settings tab doesn't appear in the user settings. Once the language is changed back to English, the client needs to be restarted.
![2017-08-02_19-30-21](https://user-images.githubusercontent.com/26047565/28919722-ab1bdf48-7846-11e7-86f2-5dbfacdfa6c6.gif)

**Comment by LewisTehMinerz** [comment]
Does DiscordInjections still work?

**Comment by TheSheepGuy** [comment]
Yes, when I change the style.css file it still changes the appearance of the client.

**Comment by Ratismal** [comment]
Ok, this is an oversight in regards to the statewatcher. I forgot about different locales. I will have to rethink this later.

Settings tabs don't have any unique identifiers so I'll probably have to hardcode positions :/

**Comment by Ratismal** [comment]
Resolved by #36
