### ISSUE TITLE
DI Settings are displayed in Server Settings

### ISSUE THREAD

**Issue by Bowser65** [DiscordInjections/DiscordInjections#41]
DI settings tabs are displayed in server settings when you are the server owner (Because of 'Delete Server' tab)

![](https://cdn.bowser65.tk/s/bz6muo10.png)

I found a small fix that I use on my plugin : check if `document.querySelectorAll('.layer .sidebar .side-2nYO0F .separator-3z7STW')[3] !== undefined`

**Comment by cking** [comment]
the reason it is there is because of the latest multilingual patch i think, if it wasn't there before.
also that selector is way to specific and may break at any time. i will see to find something "against" the false appereance of this

**Comment by Bowser65** [comment]
you can also check if `document.querySelector(".layer .sidebar a[href='https://twitter.com/discordapp']") !== null`

**Comment by cking** [comment]
yeah, checking for the social media bar is way better IMO. i could do that
