### ISSUE TITLE
New plugins not recognized by installation script

### ISSUE THREAD

**Issue by scriptHero** [DiscordInjections/DiscordInjections#50]
Quite a few new plugins have been added recently, but I can't seem to try all of them with my existing plugins.

Running `npm run install-plugins` acknowledges up to 10 plugins only. Can this number be increased through a workaround perhaps?

**Comment by Bowser65** [comment]
This is maybe blocked by a file in your plugin path (like readme.md or system files)
I found this issue yesterday but I forgot to report it

**Comment by scriptHero** [comment]
Actually, seems to be a problem with the new plugins after and including the addition of ResizeX to the Plugins repo. Installing more than 10 older plugins works fine.

**Comment by Ratismal** [comment]
This is fixed by #51
