### ISSUE TITLE
Latest Canary update breaks DI

### ISSUE THREAD

**Issue by BoxOfFlex** [DiscordInjections/DiscordInjections#59]
Latest Canary update implemented React.js v16. DI errors on modifying settings menu.

Error log: https://hastebin.com/humomapoto

**Comment by cking** [comment]
Which di versio are you using?

**Comment by BoxOfFlex** [comment]
Latest master

**Comment by cking** [comment]
Which is...?

**Comment by cking** [comment]
3.2.x.

**Comment by BoxOfFlex** [comment]
Okay apparently it was a bug with 3.2.0. Deleting `package.json` and pulling fixed.

**Comment by cking** [comment]
Fixed that bug with 3.2.2 - announced it here and the official discord channel
