### ISSUE TITLE
[Enhancement] Configurable launch options

### ISSUE THREAD

**Issue by PointyDev** [DiscordInjections/DiscordInjections#62]
Think it would be nice to have a list of launch options that we can apply to the client by setting them in the `config.json` file, e.g. `disable-smooth-scrolling`, `enable-transparent-visuals`, etc.

This can be achieved by iterating something like this in `app\index.js`: 
```js
// Disable Smooth Scrolling
content = content.replace(`app.on('ready'`, "app.commandLine.appendSwitch('disable-smooth-scrolling')" + `;app.on('ready'`)
```

This is how my file looks right now: ![ ](https://pointy.got-drunk-at-a.party/then-bought/pyro-merch/27fa0b.png)

Thanks,
Pointy

**Comment by cking** [comment]
implemented
