### ISSUE TITLE
[Suggestion ] Startup styling / editing

### ISSUE THREAD

**Issue by ThuverX** [DiscordInjections/DiscordInjections#66]
There is currently no way to style the startup app (popout?).
(This thing)
![image](https://user-images.githubusercontent.com/11523061/31772326-9dbab68c-b4df-11e7-9e4d-393dd0a7d310.png)

Are there any plans for adding support to this?
Or otherwise, may i suggest adding support for this.

It would be really cool for example to place a mod authors name there or mod icon.
Just to add the little bit of extra customization to Discord.

I hope there is away to implement this , and that it will be implemented,
ThuverX

**Comment by Aetheryx** [comment]
Hm.
As far as I can think, this would require a lightning-fast injector that would trigger before any of the native client gets loaded  
OR  
something that edits the app.asar so it never gets injected, but it exists from the start. This is kind of against DI's principles though.

**Comment by ThuverX** [comment]
Would it be possible to create an injector that runs itself before the program starts? Like even before the core program?

**Comment by cking** [comment]
I have an idea. If it works, it works. If it doesn't, then it won't be implemented

**Comment by ThuverX** [comment]
@cking welp i tried thanks anyway

**Comment by XCanG** [comment]
lol, you can easy style it by CSS, unless you really want to style it by changing DOM, but I sure, what it also possible if listening DOM for property events (when specific element added and make visible), anyway for a long time ago I make for myself "offline mode", so if my internet turn off I still can see cached content on pages, i.e. youtube videos, photos, e.t.c., after I discover if Discord websoket have a fail, I still can read messages and navigate while that screen is popup. So, the styling is:
```
.container-2oOGIt {
	opacity: .92 !important;
	background: transparent !important;
	pointer-events: none;
}
.container-2oOGIt > div {
	background: #383136 !important; /*#2f3136*/
}
.content-3dsgDG {
	align-self: flex-end;
	position: fixed;
	left: 70px;
	bottom: 65px;
	width: 240px;
	box-shadow: 0 10px 10px 5px #383136, 0 -10px 10px 5px #383136;
	clip: rect(-20px, 240px, 300px, 0px);
}
.problems-2jwWfL {
	position: fixed !important;
	top: 0px;
	bottom: unset !important;
	left: unset !important;
	right: unset !important;
	padding: 30px 20px 10px !important;
	box-shadow: 0 0 5px 10px #383136;
	pointer-events: auto;
}
```
I place boxes on that locations where they not iterrupt seeing conent, they also clicable through (except links) and color changed to a bit red for just seeing it easy if it appear.
The following styles appear on:
1) starting screen
2) reloading screen (e.g. change language)
3) server shutdown or your lost connection to internet

**Comment by cking** [comment]
@xcang he actually meant the popup window before application launch.

BTW spoiler : v4 will be able to do that

**Comment by XCanG** [comment]
Oh, he mean from updated one? Well, does it really need to be styled?.. This showed only for short time and I probably never seen this since I just turn on PC, go and do something, them back when all my programs are loaded.

**Comment by theGordHoard** [comment]
It's a small thing that people some people want. Personally I kinda want it because it'd help to just pull a theme together if everything has the same style.

**Comment by cking** [comment]
its something small and fun and doesnt cost me that much of energy.

**Comment by cking** [comment]
its done
