### ISSUE TITLE
Client crashes when entering settings/loading a channel

### ISSUE THREAD

**Issue by tilda** [DiscordInjections/DiscordInjections#73]
Running latest canary `6772` on Ubuntu 16.04. I appear to get this error (from react decoder) ![](https://oh-no-its.theworstme.me/2d3da7.png)

and this is the full error from the devtools ![](https://oh-no-its.theworstme.me/c3bf9f.png) ![](https://oh-no-its.theworstme.me/7d6ad9.png)

**Comment by Ratismal** [comment]
Seems to be an issue with how I inject react components into the DOM. Will investigate further.

**Comment by Ratismal** [comment]
I have isolated the issue to somewhere [here](https://github.com/DiscordInjections/DiscordInjections/blob/master/DomReady/Helpers.js#L10-L31). I am currently looking further into this.

**Comment by Ratismal** [comment]
@TTtie as you were the one who PRed this method of intercepting these functions, do you have any idea why it would cause this react error on Canary?

**Comment by Ratismal** [comment]
Isolated the issue. I'll release the fix shortly.

**Comment by tilda** [comment]
cool, thanks @Ratismal
