### ISSUE TITLE
Dividers not rendering properly

### ISSUE THREAD

**Issue by Aetheryx** [DiscordInjections/DiscordInjections#75]
On a few specific zoom settings, certain dividers (not all of them) will not render properly. This does not seem to be an issue with a zoom level being too low, however.  

For example, a zoom level of 80 will [render completely fine](https://why-are-you-buying-clothes-at.the-soup.store/ed926f.png). However, a zoom level of 85 will [not](https://why-are-you-buying-clothes-at.the-soup.store/af4a04.png).
Do note - the zoom level of 85 was set programmatically/manually, because the original settings jump from 80 to 90. It is not an issue with manually set values though, because the value of 75% [does not render properly](https://why-are-you-buying-clothes-at.the-soup.store/ea06bb.png) while it [is offered in the zoom settings](https://why-are-you-buying-clothes-at.the-soup.store/59552d.png).  

By overriding the `height` of the dividers to something bigger (>=1.75px from what I find) they seem to render. There is something with that as well though: if the height is overriden, [some dividers will render with the overriden height and others wont](https://why-are-you-buying-clothes-at.the-soup.store/385248.png).

**Comment by cking** [comment]
Might need recheck with v4. Will invalidate this one
