### ISSUE TITLE
Discord.JS not holding any data

### ISSUE THREAD

**Issue by Snazzah** [DiscordInjections/DiscordInjections#78]
![](https://i-need.discord.cards/e14806.png)
I believe this pertains to #77 aswell

**Comment by cking** [comment]
We will see. Right now I can't verify this error on v4. Will hold this error open in the meantime

**Comment by cking** [comment]
^  does it work on v4?

**Comment by cking** [comment]
closed on request of snazzah, seems to be fixed in v4
