### ISSUE TITLE
Some V4 Mistakes

### ISSUE THREAD

**Issue by Snazzah** [DiscordInjections/DiscordInjections#82]
Misspelled `userstyles`
https://github.com/DiscordInjections/DiscordInjections/blob/v4/engine/plugins/css/index.js#L155

can't tell if this is meant to be spelt like this
https://github.com/DiscordInjections/DiscordInjections/blob/v4/engine/plugins/mapping#L8

**`Suggestion`** Add `console.info` and `console.warn`
https://github.com/DiscordInjections/DiscordInjections/blob/v4/components/plugin.js#L168

**Comment by cking** [comment]
The mapping file is my personal wip file. But yeah that's a typo there. Thanks. Will fix

**Comment by Snazzah** [comment]
`vailed`
https://github.com/DiscordInjections/DiscordInjections/blob/v4/lib/diio/index.js#L107
